### ISSUE TITLE
Change block cursor color

### ISSUE THREAD

**Issue by unnamedcrewman** [atom/vim-mode#201]
I'm using the [Base16 Ocean Dark](https://atom.io/packages/base16-ocean-dark) theme, and I've noticed that the block cursor color doesn't show up well at all.  After changing to a number of themes, it looks like the default block cursor color in vim mode is just the exact wrong shade for these dark blue-gray themes (I've tried several also), since it looks fine in other brown/black/light syntax themes.

I can get a whiter cursor that works nicely if I change the background-color here in `vim-mode.less`:

```
.block-cursor(@visibility: visible) {
  border: 0;
  background-color: @syntax-cursor-color;
  visibility: @visibility;
  opacity: 0.5;
}
```

My understanding though, is that I shouldn't really be changing things at this level, since they will probably be overridden on updates, etc.

I've tried simply adding this css block, with updated color to my personal style file (`~/.atom/styles.less`), but this doesn't seem to work. I'm new enough at this, that I'm not sure if I need to use other css selectors or something else.

Is this cursor color issue something I can change at my personal stylesheet level, or  should I do it some other way?

**Comment by mike-engel** [comment]
Anyone find that their cursor CSS fixed stopped working after atom switched to the shadow-dom? Anyone have a fix yet? I've tried the following to no avail:

```
.block-cursor {
    background-color: rgba(0, 184, 255, 0.75);
    width: 7px !important;
    visibility: visible;
}

atom-text-editor,
atom-text-editor::shadow {
    background: #2B303B;

    &.vim-mode {
        .cursor,
        .blink-off .cursor {
            .block-cursor;
        }
    }
}
```

**Comment by pk-nb** [comment]
Fix for the shadow-dom changes @mike-engel. Looks like you'll need `.is-focused`.

Following snippet (slightly modified from one in package) works for me.

```
atom-text-editor.vim-mode.command-mode.is-focused,
atom-text-editor.vim-mode.operator-pending-mode.is-focused,
atom-text-editor.vim-mode.visual-mode.is-focused
{
  &::shadow, // shadow-DOM enabled
  &          // shadow-DOM disabled
  {
    .cursor, .cursor.blink-off {
      background-color: #fff;
      opacity: 0.3;
      visibility: visible;
    }
  }
}

```

**Comment by mike-engel** [comment]
Thanks @pk-nb, worked for me.

**Comment by rafa2000** [comment]
It worked for me too. Thanks @pk-nb.

Here is my full `styles.less`. It includes additional styling for a red cursor and a red bracket matcher (which looks great using the `Lucario` syntax theme), and a more pleasant `tree-view` spacing. I included it here, because it took me some time to clean it up. I hope it saves someone a little time.

```less
/*
 * Your Stylesheet
 *
 * This stylesheet is loaded when Atom starts up and is reloaded automatically
 * when it is changed.
 *
 * If you are unfamiliar with LESS, you can read more about it here:
 * http://www.lesscss.org
 */

@import "ui-variables";

/*
 pk-nb
 Jan 23, 2015
 same url
 
 rafa2000
 Feb 28, 2015
 mashed up with:
   + Red Cursor in Vim mode
   + Red Bracket Matcher
   + Styled Tree-View
*/
atom-text-editor.vim-mode.command-mode.is-focused,
atom-text-editor.vim-mode.operator-pending-mode.is-focused,
atom-text-editor.vim-mode.visual-mode.is-focused
{
  &::shadow, // shadow-DOM enabled
  &          // shadow-DOM disabled
  {
    /* cursor color */
    .cursor, .cursor.blink-off {
      background-color: #f00;
      opacity: 0.3;
      visibility: visible;
    }
    /* special characters */
    .invisible-character {
      opacity: 0.2;
    }
    /* indent guide */
    .indent-guide {
      opacity: 1.0;
    }
    /* bracket matcher */
    .bracket-matcher {
      // border-bottom: 1px solid green;
      background-color: red !important;
      opacity: 0.6 !important;
      width: 0.63em !important;
    }
  }
}

/* A more compact tree view */
.tree-view {
  font-size: 10px;
  .list-item {
    line-height: 18px !important;
  }
  .selected:before, .selected:before {
    height: 16px !important;
  }
  .icon:before {
    font-size: 9px;
    width: 8px;
    height: 9px;
    opacity: 0.6;
    position: relative;
    top: 0px;
    margin-right: 5px !important;
  }
  .header:before {
    font-size: 9px !important;
    opacity: 0.6;
  }
}
```

**Comment by erickbarron** [comment]
Hello, I have been able to change to the block cursor color to one that I like. But I am unable to get the cursor to blink, anyone know why? Isn't the visibility: visible; suppose to do that?

![vim-cursor](https://cloud.githubusercontent.com/assets/3500392/7187437/4982d2c6-e425-11e4-88b2-8afa7041a85f.gif)
```less
@import "ui-variables";

.tree-view {

}

.editor {

}

.editor .cursor {

}

atom-text-editor.vim-mode.command-mode.is-focused,
atom-text-editor.vim-mode.operator-pending-mode.is-focused,
atom-text-editor.vim-mode.visual-mode.is-focused
{
  &::shadow, // shadow-DOM enabled
  &          // shadow-DOM disabled
  {
    /* cursor color */
    .cursor, .cursor.blink-off {
      background-color: rgba(59,117,140,1);
      visibility: visible !important;
    }
    /* bracket matcher */
    .bracket-matcher {
      background-color: rgb(59,117,140) !important;
      opacity: 0.6 !important;
      width: 0.63em !important;
    }
  }
}
```

**Comment by jacekkopecky** [comment]
You have `visibility: visible` both for .cursor and .cursor.blink-off - one of them should have `visibility: hidden` or some such, I suspect.

**Comment by erickbarron** [comment]
@jacekkopecky , nah that doesn't seem to solve it, I tried to do it with different combinations.

**Comment by sgtpepper43** [comment]
`.blink-off` is applied to the parent of `.cursor`. So put `visibility: hidden` in `.blink-off .cursor` instead.

**Comment by erickbarron** [comment]
@sgtpepper43, Awesome, that works. Thanks a lot!!! :smile:

**Comment by sgtpepper43** [comment]
An update apparently broke the currently posted css, so in case anyone else stumbles in here looking for that, you have to include `.is-focused` now
```
atom-text-editor.vim-mode.normal-mode,
atom-text-editor.vim-mode.operator-pending-mode,
atom-text-editor.vim-mode.visual-mode
{
  &, &.is-focused {
    &::shadow, // shadow-DOM enabled
    &          // shadow-DOM disabled
    {
      /* cursor color */
      .cursor {
        background-color: rgba(85, 181, 219, 0.6);
        border: 1px solid rgba(85, 181, 219, 0.9);
        border-color: rgba(85, 181, 219, 0.9) !important;
        opacity: 1;
        visibility: visible;
        transition: background-color 0.4s;
      }
      .blink-off .cursor {
        background-color: transparent;
      }
    }
  }
}
```

**Comment by pk-nb** [comment]
Thank you @sgtpepper43! Works great.

**Comment by crucialfelix** [comment]
Here's a bit of status bar:


```less
.status-bar-vim-mode-normal,
.status-bar-vim-mode-insert,
.status-bar-vim-mode-visual {
  font-weight: bold;
  text-align: center;
  font-size: 1.5em;
  width: 18rem;
  text-transform: uppercase;
}

@normal-bg: rgb(105, 238, 103);
.status-bar-vim-mode-normal {
  background: @normal-bg;
  color: rgb(4, 111, 11);
}

.status-bar-vim-mode-insert {
  background: rgb(7, 193, 242);
  color: white;
}

.status-bar-vim-mode-visual {
  background: rgb(255, 206, 98);
  color: rgb(168, 117, 5);
}
```

Best would be if vim-mode just sets a class on the workspace.
Then we could write styles that change the whole status bar like powerline or just change the coloring of the active tab.

I like the corner-of-my-eye effect of a strong color indicating what mode I'm in.

![screen shot 2015-12-19 at 17 34 06](https://cloud.githubusercontent.com/assets/218738/11914103/d5b8e5c8-a676-11e5-943b-811a2de38d77.png)

**Comment by ktraff** [comment]
For those looking to modify the cursor with vim-mode-plus, you can use this snippet in your ~/.atom/styles.less:

```less
atom-text-editor.vim-mode-plus.normal-mode,
atom-text-editor.vim-mode-plus.visual-mode,
{
  &.is-focused {
    .cursor {
      background-color: #FFF !important;
      visibility: visible;
    }
  }
}
```
