### ISSUE TITLE
Less subtle mode indication

### ISSUE THREAD

**Issue by lmartins** [atom/vim-mode#585]
I think usability would improve with something similar to powerline for mode indication, making it clear by color codes which mode we are at any give moment.

**Comment by maxbrunsfeld** [comment]
You should be able to apply styling to [these classes](https://github.com/atom/vim-mode/blob/master/lib/status-bar-manager.coffee#L4) ('status-bar-vim-mode-insert` etc) in your `styles.less`.

e.g.
```less
#status-bar-vim-mode {
  font-size: 18px;
  font-weight: bold;
}

.status-bar-vim-mode-insert {
  color: red;
}
```
