### ISSUE TITLE
Change command mode cursor to default

### ISSUE THREAD

**Issue by smaili** [atom/vim-mode#750]
Right now, when in command mode or insert mode, the cursor is always `text`.  I've tried adding this selector:

```
atom-text-editor.vim-mode.command-mode {
    cursor: default;
}
```

but unfortunately that is not working.

**Comment by bronson** [comment]
Just screwing around with the inspector, this seems to work:

```css
atom-text-editor.vim-mode.command-mode::shadow .editor-contents--private {
    cursor: default;
}
```

Dunno if that's anywhere near correct.

**Comment by msmaili** [comment]
You're absolutely right, it does seem to work.  Although I do agree the selector isn't the most pretty :)

Is there a chance to push this as default behavior?  I think intuitively, when the editor is in command mode, it doesn't really make sense to show the cursor as text.  There's been a few times I first look to the mouse cursor and not the blinking cursor, and because it shows the text cursor I think I'm in insert mode.

**Comment by bronson** [comment]
I say, create a pull request and find out.  :)

**Comment by bronson** [comment]
Pretty sure this will be the idiomatic way to do this:

```less
atom-text-editor.vim-mode.command-mode
{
  &::shadow,
  &
  {
    .is-focused {
      cursor: default;
    }
  }
}
```

Think you could create a pull request that adds that to styles/vim-mode.less?

**Comment by bronson** [comment]
But that, of course, fails when hovering the cursor over an unfocused pane.

`.editor-contents--private` is the only selector I can find that allows us to override the default.  So here's my most recent guess:

```less
atom-text-editor.vim-mode.command-mode
{
  &::shadow,
  &
  {
    .editor-contents--private {
      cursor: default;
    }
  }
}
```
