### ISSUE TITLE
Mode indicator

### ISSUE THREAD

**Issue by sho-87** [atom/vim-mode#958]
Is it possible, either through a setting I missed or some config I could add, to change the colour of the status bar depending on what mode I'm currently in? Or at least some way to make mode indication clearer?

I know there is text in the status bar to indicate my current mode, but its pretty difficult to see when youre working quickly

**Comment by maxbrunsfeld** [comment]
Try something like this:

```less
#status-bar-vim-mode {
  &.status-bar-vim-mode-insert {
    color: red;
    font-weight: bold;
  }

  &.status-bar-vim-mode-visual {
    color: green;
    font-weight: bold;
  }
}
```

Let me know if you have any further questions!
